CRITICAL - 2022-11-09 08:19:39 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Database\MySQLi\Connection.php on line 208.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2022-11-09 08:20:03 --> Error connecting to the database: mysqli_sql_exception: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu in C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('mysql-seetalk.a...', 'seetalk', 'Btssio82300', 'seetalk_bdd', 3306, '', 0)
#1 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('select * from U...')
#4 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\app\Controllers\Gestion.php(12): CodeIgniter\Model->__call('query', Array)
#5 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\CodeIgniter.php(907): App\Controllers\Gestion->gestion_utilisateurs()
#6 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestion))
#7 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu in C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\Model.php(768): CodeIgniter\Database\BaseConnection->query('select * from U...')
#3 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\app\Controllers\Gestion.php(12): CodeIgniter\Model->__call('query', Array)
#4 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\CodeIgniter.php(907): App\Controllers\Gestion->gestion_utilisateurs()
#5 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestion))
#6 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\SeeTalk\Code\SeeTalk\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-09 08:20:03 --> Unable to connect to the database.
Main connection [MySQLi]: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(768): CodeIgniter\Database\BaseConnection->query('select * from UTILISATEUR')
 3 APPPATH\Controllers\Gestion.php(12): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Gestion->gestion_utilisateurs()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gestion))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-09 10:21:09 --> Fichier non valide : contact.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('contact.php')
 2 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('contact', [], true)
 3 APPPATH\Controllers\Pages.php(57): view('contact')
 4 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\Pages->contact()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-11-09 10:50:31 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 154.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-11-09 10:50:31 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 135.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-11-09 10:50:31 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 135.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-11-09 10:50:31 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Session\Handlers\FileHandler.php on line 135.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
